# YAML linting configuration
extends: default

rules:
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  document-start: disable # Allow files without --- at start
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
