apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eventsphere-cluster
  region: us-east-1
  version: "1.34"
  tags:
    Project: EventSphere
    Environment: Production
    ManagedBy: eksctl

# VPC Configuration
# eksctl will create a new VPC with public and private subnets across all AZs
vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable  # One NAT Gateway per AZ for high availability
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

# IAM Configuration
iam:
  withOIDC: true  # Required for IRSA (IAM Roles for Service Accounts)
  serviceAccounts:
    # AWS Load Balancer Controller
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    # Cluster Autoscaler
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true
    # EBS CSI Driver
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    
    # External Secrets Operator
    - metadata:
        name: external-secrets
        namespace: external-secrets-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
    # Fluent Bit for CloudWatch Logs
    - metadata:
        name: fluent-bit
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

# CloudWatch Logging
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]  # Enable all log types: api, audit, authenticator, controllerManager, scheduler

# Add-ons
addons:
  # VPC CNI (required for pod networking)
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  # CoreDNS (required for DNS resolution)
  - name: coredns
    version: latest

  # kube-proxy (required for service networking)
  - name: kube-proxy
    version: latest

  # EBS CSI Driver (for persistent volumes)
  - name: aws-ebs-csi-driver
    version: latest

# Managed Node Groups
# Using managed node groups provides better lifecycle management
managedNodeGroups:
  - name: eventsphere-mng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 50
    volumeType: gp3
    volumeEncrypted: true
    #availabilityZones: ["us-east-1a", "us-east-1b"]
    ssh:
      allow: false
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    labels:
      role: workload
      environment: production
    tags:
      NodeGroup: eventsphere-mng-1
      Purpose: Workload

  - name: eventsphere-mng-2
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 50
    volumeType: gp3
    volumeEncrypted: true
    #availabilityZones: ["us-east-1a", "us-east-1b"]
    ssh:
      allow: false
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    labels:
      role: workload
      environment: production
    tags:
      NodeGroup: eventsphere-mng-2
      Purpose: Workload




